###
GET http://localhost:4000/api/employees

###
POST http://localhost:4000/api/employees
Content-Type: application/json

{
   "name": "Jesus",
   "position": "Jr. Developer",
   "office": "Rome",
   "salary": "2000"
}

###
GET http://localhost:4000/api/employees/63e322b47ec4ff255bfc5153

###
DELETE http://localhost:4000/api/employee/63e322d27ec4ff255bfc5154

###
PUT http:localhost:4000/api/employee/63e322b47ec4ff255bfc5153
Content-Type: application/json

{
    "salary": 1000000
}